name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: write
  deployments: write
  statuses: write

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    outputs:
      source-code-changed: ${{ steps.check-code-changes.outputs.src }}
      deploy-web: ${{ steps.check-code-changes.outputs.web }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check for code changes
        id: check-code-changes
        run: |
          if [ '${{ github.ref }}' = 'refs/heads/main' ]; then
            echo "On main branch. Running all checks."
            echo "src=true" >> $GITHUB_OUTPUT
            echo "web=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Checking for code changes..."
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -E '^.*\.(css|html|[cm]?js|json|tsx?|ya?ml)'; then
            echo "Source code changes detected."
            echo "src=true" >> $GITHUB_OUTPUT
          else
            echo "No source code changes detected."
            echo "src=false" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only origin/main...HEAD | grep -E '^packages/(shared|web)/' | grep -v '.*\.test\.tsx?'; then
            echo "Web App changes detected."
            echo "web=true" >> $GITHUB_OUTPUT
          else
            echo "No Web App changes detected."
            echo "web=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type-check
        if: steps.check-code-changes.outputs.src == 'true'
        run: |
          echo "::add-matcher::.github/problem-matchers/tsc.json"
          npm run typecheck
          echo "::remove-matcher owner=tsc::"

      - name: Test
        if: steps.check-code-changes.outputs.src == 'true'
        run: CI=true npm test

      - name: Lint
        if: steps.check-code-changes.outputs.src == 'true'
        run: |
          echo "::add-matcher::.github/problem-matchers/eslint.json"
          npm run lint
          echo "::remove-matcher owner=eslint::"

      - name: Check formatting
        # skip formatting check on main branch to avoid failing main branch status checks on formatting rule changes
        # (i.e. a PR could be merged that is not on the latest prettier config and we don't want this workflow to fail on main).
        if: github.ref != 'refs/heads/main'
        run: |
          if git diff --name-only --diff-filter=d origin/main...HEAD | grep -F 'prettier.config.ts'; then
            # if the config file has changed, then run prettier on all files
            npm run format
          else
            # only run prettier on the files that have changed
            npx prettier -u --write $(git diff --name-only --diff-filter=d -z origin/main...HEAD | xargs -0)
          fi
          if ! git diff --exit-code --quiet; then
            echo "::error::Code is not formatted. Run 'npm run format' locally and commit the changes."
            git diff --name-only
            exit 1
          fi

  deploy-web-preview:
    name: Web Preview
    runs-on: ubuntu-latest
    # always skip deploys on the main branch because Netlify does this automatically
    if: github.ref != 'refs/heads/main' && needs.build.outputs.deploy-web == 'true'
    needs:
      - build
    outputs:
      web_url: ${{ steps.deploy-web-preview.outputs.deploy-url || 'https://ecookbook.netlify.app' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build the Web App
        run: npm run build --workspace=packages/web

      - name: Deploy to Netlify
        id: deploy-web-preview
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./packages/web/build/client"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN_DEPLOY_PROD }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROJECT_ID_PROD }}
        timeout-minutes: 3
